project_name: fastauto

builds:
  - id: fastauto
    main: ./cmd/fastauto/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: fastauto

archives:
  - formats: [tar.gz]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

release:
  prerelease: auto

