project_name: fastauto

builds:
  - id: fastauto
    main: ./cmd/fastauto/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: fastauto

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

release:
  prerelease: auto

nfpms:
  - id: fastauto
    package_name: fastauto
    homepage: "https://github.com/gigahidjrikaaa/fastauto"
    maintainer: "fastauto contributors"
    description: "Fast, safe autopull + auto-deploy for any Git repo"
    license: MIT
    formats: [deb, rpm, apk]
    bindir: "/usr/local/bin"
    builds:
      - fastauto
